from enum import Enum

class AuditCategory(str, Enum):
    BUSINESS = "BUSINESS"
    SECURITY = "SECURITY"
    SYSTEM = "SYSTEM"
    LIFECYCLE = "LIFECYCLE"

class AuditEvent(str, Enum):
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_CLOSED = "SESSION_CLOSED"
    ORDER_TRACKING = "ORDER_TRACKING"
    ORDER_CANCELLATION = "ORDER_CANCELLATION"
    PHONE_VERIFICATION = "PHONE_VERIFICATION"
    COMPLAINT_CREATION = "COMPLAINT_CREATION"
    HUMAN_HANDOFF = "HUMAN_HANDOFF"
    RATE_LIMIT = "RATE_LIMIT"
    LLM_INTERACTION = "LLM_INTERACTION"
    SYSTEM_EXCEPTION = "SYSTEM_EXCEPTION"

class AuditOutcome(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    WARNING = "WARNING"
    INFO = "INFO"
