from enum import Enum

class ErrorCode(str, Enum):
    ERR_DB_TIMEOUT = "ERR_DB_TIMEOUT"
    ERR_DB_CONNECTION = "ERR_DB_CONNECTION"
    ERR_RECORD_NOT_FOUND = "ERR_RECORD_NOT_FOUND"
    ERR_PHONE_MISMATCH = "ERR_PHONE_MISMATCH"
    ERR_RATE_LIMIT_EXCEEDED = "ERR_RATE_LIMIT_EXCEEDED"
    ERR_LLM_TIMEOUT = "ERR_LLM_TIMEOUT"
    ERR_LLM_QUOTA = "ERR_LLM_QUOTA"
    ERR_LLM_AUTH = "ERR_LLM_AUTH"
    ERR_UNKNOWN = "ERR_UNKNOWN"
